name: files
description: dahliaOS Files.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: any

  collection: ^1.16.0

  ffi: ^2.0.1
  filesize: ^2.0.1
  flutter:
    sdk: flutter

  intl: any
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2

  material_design_icons_flutter: ^5.0.5955-rc.1 
  mime: ^1.0.0

  path: ^1.8.2
  path_provider: ^2.0.2
  provider: ^6.0.0

  url_launcher: any
  windows_path_provider:
    git:
      url: https://github.com/HrX03/windows_path_provider.git
  xdg_directories: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.2
  isar_generator: ^3.0.2
  lint: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/locales/
    - lib/assets/icons/
