name: files
description: dahliaOS Files.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: any
  filesize: ^2.0.1
  intl: any
  isar: ^0.4.0
  isar_flutter_libs: ^0.4.0
  material_design_icons_flutter: ^5.0.5955-rc.1 
  mime: ^1.0.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  url_launcher: any
  ffi: ^1.1.2
  windows_path_provider:
    git:
      url: https://github.com/HrX03/windows_path_provider.git
  xdg_directories: ^0.2.0

dev_dependencies:
  build_runner: ^2.0.5
  lint: ^1.8.1
  isar_generator: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/locales/
    - lib/assets/icons/
